//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebFormObligatorio.AlumnoServicioRemoto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/ServicioWCFObligatorio")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.cedulaField, value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlumnoServicioRemoto.IAlumnoService")]
    public interface IAlumnoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/ObtenerAlumno", ReplyAction="http://tempuri.org/IAlumnoService/ObtenerAlumnoResponse")]
        ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno ObtenerAlumno(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/ObtenerAlumno", ReplyAction="http://tempuri.org/IAlumnoService/ObtenerAlumnoResponse")]
        System.Threading.Tasks.Task<ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno> ObtenerAlumnoAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/ObtenerTodos", ReplyAction="http://tempuri.org/IAlumnoService/ObtenerTodosResponse")]
        ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno[] ObtenerTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/ObtenerTodos", ReplyAction="http://tempuri.org/IAlumnoService/ObtenerTodosResponse")]
        System.Threading.Tasks.Task<ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno[]> ObtenerTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/AgregarAlumno", ReplyAction="http://tempuri.org/IAlumnoService/AgregarAlumnoResponse")]
        bool AgregarAlumno(ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlumnoService/AgregarAlumno", ReplyAction="http://tempuri.org/IAlumnoService/AgregarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> AgregarAlumnoAsync(ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno alumno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlumnoServiceChannel : ClienteWebFormObligatorio.AlumnoServicioRemoto.IAlumnoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoServiceClient : System.ServiceModel.ClientBase<ClienteWebFormObligatorio.AlumnoServicioRemoto.IAlumnoService>, ClienteWebFormObligatorio.AlumnoServicioRemoto.IAlumnoService {
        
        public AlumnoServiceClient() {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno ObtenerAlumno(string cedula) {
            return base.Channel.ObtenerAlumno(cedula);
        }
        
        public System.Threading.Tasks.Task<ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno> ObtenerAlumnoAsync(string cedula) {
            return base.Channel.ObtenerAlumnoAsync(cedula);
        }
        
        public ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno[] ObtenerTodos() {
            return base.Channel.ObtenerTodos();
        }
        
        public System.Threading.Tasks.Task<ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno[]> ObtenerTodosAsync() {
            return base.Channel.ObtenerTodosAsync();
        }
        
        public bool AgregarAlumno(ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno alumno) {
            return base.Channel.AgregarAlumno(alumno);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAlumnoAsync(ClienteWebFormObligatorio.AlumnoServicioRemoto.Alumno alumno) {
            return base.Channel.AgregarAlumnoAsync(alumno);
        }
    }
}
